### ISSUE TITLE
Значение вероятности выживания. 

### ISSUE THREAD

**Issue by QuizeS** [QuizeS/Magnus-Expansion#10]
Вероятность выживания велика по сравнению с данными в статье значениями.  В коде присутсвует ошибка.

**Comment by aakampf** [comment]
> Вероятность выживания велика по сравнению с данными в статье значениями. В коде присутсвует ошибка. Ошибка связана с расчетом углов смешивания. Проблемы две, при изменении энергии вероятность выживания меняется в 3-5 знаке, после запятой, что не согласуется с графиком приведенном в статье. И второе, мы знаем только квадраты cos-ов и sin-ов углов смешивания нейтрино. В алгоритме импользуются значения  cos-ов и sin-ов без квадратов. Вопрос состоит в том, какой знак брать у cos-ов и sin-ов без квадратов ?

**Comment by vp1981** [comment]
2QuizeS
ты задал интересный вопрос, поскольку это **один** из актуальных вопрос — в какой четверти располагаются углы. Известен лишь квадрат синуса углов смешивания, насчёт его значения (положительный он или отрицательный) — есть лишь предположения. Давай считать пока, что углы расположены в первой четверти, т.к. и синус и косинус углов — положительные.

Насчёт ошибки расчёта. Один моменты ты исправил, но есть ещё один в функции ME4 (реализация алгоритма), он связан с тем, что должна содержать матрица A, поскольку от неё потом рассчитывается матричная экспонента.
